// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LEGO Remote",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "LEGO Remote",
            targets: ["AppModule"],
            bundleIdentifier: "com.bricklife.playgrounds.lego-remote",
            teamIdentifier: "UV6TAX3ANB",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .bluetoothAlways(purposeString: "ハブとの接続にBluetoothを利用します")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/bricklife/BoostBLEKit", "3.5.0"..<"4.0.0"),
        .package(url: "https://github.com/bricklife/AsyncBluetooth", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "BoostBLEKit", package: "BoostBLEKit"),
                .product(name: "AsyncBluetooth", package: "AsyncBluetooth")
            ],
            path: "."
        )
    ]
)